# Project: Prueba_proyecto
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o EdgeData.o ListEdge.o ListVertex.o Vertex.o
LINKOBJ  = main.o EdgeData.o ListEdge.o ListVertex.o Vertex.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Prueba_proyecto.exe
CXXFLAGS = $(CXXINCS) -std=c++11   -lwsock32
CFLAGS   = $(INCS) -std=c++11   -lwsock32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

EdgeData.o: EdgeData.cpp
	$(CPP) -c EdgeData.cpp -o EdgeData.o $(CXXFLAGS)

ListEdge.o: ListEdge.cpp
	$(CPP) -c ListEdge.cpp -o ListEdge.o $(CXXFLAGS)

ListVertex.o: ListVertex.cpp
	$(CPP) -c ListVertex.cpp -o ListVertex.o $(CXXFLAGS)

Vertex.o: Vertex.cpp
	$(CPP) -c Vertex.cpp -o Vertex.o $(CXXFLAGS)
